### ISSUE TITLE
Error: Unable to resolve action `saucelabs/saucectl-run-action@v2`, unable to find version `v2`

### ISSUE THREAD

**Issue by ghost** [saucelabs/saucectl-run-action#17]
I tried updating the version of the action in my workflow from v1 to v2 to get rid of nodejs compatibility warnings but now the workflow fails with:

Error: Unable to resolve action `saucelabs/saucectl-run-action@v2`, unable to find version `v2`

**Comment by alexplischke** [comment]
Sorry about that! You should be good now if you try again 👍
