### ISSUE TITLE
Playwright Custom Reporter not running when integrating with SauceLabs

### ISSUE THREAD

**Issue by jpaxtonrs** [saucelabs/saucectl-run-action#20]
I have a Custom Reporter that I'm running for my Playwright tests.
It is defined in the Playwright configuration file and I'm feeding it to the `.sauce/config.yml` for SauceLabs to use.

When running the Playwright tests on my local without SauceLabs, the reporter is properly fired off and running as expected.
However, when I run the Playwright tests against SauceLabs using the `saucectl` CLI and the `saucectl-run-action` GitHub Action, it is not working and seems to be using another reporter.

I see that there is a reporter object in the Playwright SauceLabs Configuration YAML:
https://docs.saucelabs.com/web-apps/automated-testing/playwright/yaml/#reporters

Could this be what is overriding my Custom Reporter?

My Custom Reporter `./testrail/reporter/testrail.reporter.ts` looks something like:
```
import { Reporter } from '@playwright/test/types/testReporter';

class TestRailReporter implements Reporter {
  
  onBegin(config, suite): void {
    // logic
  }

  onTestBegin(test, result): void {
    // logic
  }

  onTestEnd(test, result): void {
    // logic
  }

  onEnd(result): void | Promise<void> {
    // logic
  }
}

export default TestRailReporter;
```

In my playwright.sauce.config.ts, I have the following reporter being used:
```
const config: PlaywrightTestConfig = {
  ...
  reporter: './testrail/reporter/testrail.reporter.ts',
  ...
}
```

In my `.sauce/config.yml`, I have the following:
```
...
playwright:
  version: package.json
  configFile: playwright.sauce.config.ts
...
```

Any feedback would be greatly appreciated as I really need this Custom Reporter to be executed while running my Playwright tests in SauceLabs.

Thanks.

**Comment by alexplischke** [comment]
Indeed, we set the reporters to `list`, `junit` and our own internal reporter, thereby overriding your reporter settings. As it stands, I don't see a way to work around this limitation. I'll create a feature request ticket internally 👍

**Comment by jpaxtonrs** [comment]
Thank you! Looking forward to the resolution!

**Comment by alexplischke** [comment]
Actually, I did end up finding a viable workaround!

Try this:
```
const config: PlaywrightTestConfig = {
  reporter: [['./testrail/reporter/testrail.reporter.ts']],
}
```

**Comment by jpaxtonrs** [comment]
The Custom Reporter is working as expected when the Playwright tests run in SauceLabs using your workaround!

I could take a guess on why this is working; however, it would be just a guess.
How come providing an `Array<Array<string>>` for the `reporter` in the configuration works over providing a `string` for the `reporter`?

**Comment by alexplischke** [comment]
There's a logic in place that concats arrays together, but if the value is a primitive, and we have an explicit setting for it, ours takes precedence (this is so we can override certain user settings so that playwright functions or integrates better with our cloud).

**Comment by jpaxtonrs** [comment]
Ah ok, makes sense.
Maybe adding a warning/info message about that here to avoid explaining it again: https://docs.saucelabs.com/web-apps/automated-testing/playwright/yaml/#reporters

Thanks!
