### ISSUE TITLE
arm64 support

### ISSUE THREAD

**Issue by achmyr** [saucelabs/saucectl-run-action#27]
There's no better time to introduce new architecture into the Saucectl Action!

We ran builds on cloud-based arm64 Macs and got the "Undefined: browser_download_url" error. The reason for this is that the `arm64` architecture is not recognized by the run-action, though the underlying `saucectl` release has it available. 

I've added a [small fix ](https://github.com/saucelabs/saucectl-run-action/pull/26) to alleviate the immediate problem of the availability of `ctl` on arm64 mac runners, but from what I understand, the arm64 filename is not following the naming convention for `32-bit` and `64-bit` [here](https://github.com/saucelabs/saucectl/blob/dfbce5d91ab6bb9093a735554928097955b86e26/.goreleaser.yml#L45). If that was not intentional, then I'll update PR with new name.

PR: #26

**Comment by alexplischke** [comment]
Closed via https://github.com/saucelabs/saucectl-run-action/pull/26
