### ISSUE TITLE
4.2.0 uses node22 which is not supported

### ISSUE THREAD

**Issue by latsson** [saucelabs/saucectl-run-action#39]
## The Problem

Getting this error when using 4.2.0

> Error: System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter ''using: node22' is not supported, use 'docker', 'node12', 'node16' or 'node20' instead.')

## Environment

- Version that exhibits the issue: 4.2.0
- Last version that did not exhibit the issue (if applicable): 4.1.0
- Desktop OS/version:

## Code To Reproduce Issue [ Nice To Have ]

`uses: saucelabs/saucectl-run-action@v4`
or
`uses: saucelabs/saucectl-run-action@v4.2.0`

**Comment by tianfeng92** [comment]
Got this issue fixed in https://github.com/saucelabs/saucectl-run-action/pull/40 Thanks for reporting!
